// Word database. Kept in its own file so categories/words can be
// expanded independently of game logic.

export const WORD_BANK: Record<string, string[]> = {
  Actor: [
    "Salman Khan",
    "Shah Rukh Khan",
    "Aamir Khan",
    "Ranbir Kapoor",
    "Ranveer Singh",
    "Fawad Khan",
    "Leonardo DiCaprio",
    "Tom Cruise",
    "Dwayne Johnson",
    "Robert Downey Jr.",
    "Keanu Reeves",
    "Chris Hemsworth",
    "Ryan Reynolds",
    "Johnny Depp",
    "Will Smith",
  ],

  Movies: [
    "Interstellar",
    "Titanic",
    "Inception",
    "The Dark Knight",
    "Joker",
    "Avengers",
    "Harry Potter",
    "Avatar",
    "The Matrix",
    "Jurassic Park",
    "3 Idiots",
    "Dangal",
    "Pathaan",
    "Oppenheimer",
    "Barbie",
  ],

  Food: [
    "Pizza",
    "Burger",
    "Biryani",
    "Sushi",
    "Pasta",
    "Ice Cream",
    "Noodles",
    "Tacos",
    "Fried Chicken",
    "Lasagna",
    "Nihari",
    "Karahi",
    "Haleem",
    "Gol Gappay",
    "Shawarma",
  ],

  Animals: [
    "Lion",
    "Tiger",
    "Elephant",
    "Dolphin",
    "Penguin",
    "Wolf",
    "Giraffe",
    "Kangaroo",
    "Panda",
    "Cheetah",
    "Monkey",
    "Crocodile",
    "Horse",
    "Eagle",
    "Snake",
  ],

  Countries: [
    "Pakistan",
    "India",
    "Japan",
    "Turkey",
    "Canada",
    "Australia",
    "Brazil",
    "United Kingdom",
    "France",
    "Germany",
    "United States",
    "Saudi Arabia",
    "UAE",
    "Italy",
    "South Korea",
  ],

  Games: [
    "Minecraft",
    "Roblox",
    "Fortnite",
    "GTA V",
    "Valorant",
    "FIFA",
    "Among Us",
    "Call of Duty",
    "Apex Legends",
    "Counter-Strike",
    "PUBG",
    "Free Fire",
    "League of Legends",
    "Elden Ring",
    "Red Dead Redemption 2",
  ],

  Sports: [
    "Cricket",
    "Football",
    "Basketball",
    "Tennis",
    "Boxing",
    "Formula 1",
    "Golf",
    "Hockey",
    "Wrestling",
    "Volleyball",
    "Badminton",
    "Baseball",
    "Swimming",
    "MMA",
    "Table Tennis",
  ],

  Singers: [
    "Atif Aslam",
    "Arijit Singh",
    "Taylor Swift",
    "The Weeknd",
    "Drake",
    "Ed Sheeran",
    "Justin Bieber",
    "Bruno Mars",
    "Adele",
    "Billie Eilish",
    "Ali Zafar",
    "Rahat Fateh Ali Khan",
    "AP Dhillon",
    "Diljit Dosanjh",
    "Selena Gomez",
  ],

  Superheroes: [
    "Spider-Man",
    "Batman",
    "Superman",
    "Iron Man",
    "Thor",
    "Hulk",
    "Captain America",
    "Wonder Woman",
    "Deadpool",
    "Black Panther",
    "The Flash",
    "Aquaman",
    "Wolverine",
    "Doctor Strange",
    "Captain Marvel",
  ],

  Cars: [
    "BMW",
    "Mercedes-Benz",
    "Audi",
    "Lamborghini",
    "Ferrari",
    "Porsche",
    "Toyota",
    "Honda",
    "Nissan",
    "Ford",
    "Tesla",
    "Range Rover",
    "Bugatti",
    "McLaren",
    "Supra",
  ],

  Memes: [
    "Gigachad",
    "Trollface",
    "Pepe the Frog",
    "Doge",
    "Rickroll",
    "Distracted Boyfriend",
    "Drake Hotline Bling",
    "This Is Fine",
    "Wojak",
    "Among Us Sus",
    "Stonks",
    "NPC Meme",
    "Skibidi Toilet",
    "Sigma",
    "Bombastic Side Eye",
  ],

  Desi_Memes: [
    "Nana Patekar Angry",
    "Aunty Calling",
    "Pawri Ho Rahi Hai",
    "Moye Moye",
    "Moye Moye Guy",
    "Vada Pav Girl",
    "Orhan Awatramani",
    "Jalebi Baby",
    "Binod",
    "Rasode Mein Kaun Tha",
    "Bhai Kya Kar Raha Hai",
    "Aye Hayeee",
    "Kya Mast Joke Mara Re",
    "Emotional Damage",
    "Bhai Ne Kya Pehna Hai",
  ],

  Internet_People: [
    "MrBeast",
    "IShowSpeed",
    "Kai Cenat",
    "Adin Ross",
    "HasanAbi",
    "xQc",
    "PewDiePie",
    "KSI",
    "Logan Paul",
    "Jake Paul",
    "Khaby Lame",
    "Andrew Tate",
    "N3on",
    "Cbum",
    "CaseOh",
  ],

  Celebrities: [
    "Kim Kardashian",
    "Kylie Jenner",
    "Zendaya",
    "The Weeknd",
    "Selena Gomez",
    "Rihanna",
    "Justin Bieber",
    "Tom Holland",
    "Jenna Ortega",
    "Emma Watson",
    "Cristiano Ronaldo",
    "Lionel Messi",
    "Virat Kohli",
    "Babar Azam",
    "Mahira Khan",
  ],

  TV_Shows: [
    "Breaking Bad",
    "Game of Thrones",
    "Stranger Things",
    "The Office",
    "Friends",
    "Wednesday",
    "Money Heist",
    "Peaky Blinders",
    "The Boys",
    "Squid Game",
    "Dark",
    "Cobra Kai",
    "Rick and Morty",
    "The Simpsons",
    "Better Call Saul",
  ],

  Brands: [
    "Nike",
    "Adidas",
    "Apple",
    "Samsung",
    "Coca-Cola",
    "Pepsi",
    "McDonald's",
    "KFC",
    "Starbucks",
    "Gucci",
    "Louis Vuitton",
    "Rolex",
    "Netflix",
    "PlayStation",
    "Xbox",
  ],

  Places: [
    "Eiffel Tower",
    "Burj Khalifa",
    "Times Square",
    "Statue of Liberty",
    "Great Wall of China",
    "Taj Mahal",
    "Makkah",
    "Madina",
    "Dubai",
    "New York",
    "London",
    "Paris",
    "Tokyo",
    "Maldives",
    "Mount Everest",
  ],

  Supernatural: [
    "Ghost",
    "Vampire",
    "Zombie",
    "Werewolf",
    "Witch",
    "Demon",
    "Angel",
    "Dragon",
    "Alien",
    "Mermaid",
    "Kraken",
    "Mummy",
    "Siren",
    "Grim Reaper",
    "Frankenstein",
  ],

  Everyday_Things: [
    "Phone",
    "Laptop",
    "Headphones",
    "Toothbrush",
    "Mirror",
    "Backpack",
    "Umbrella",
    "Wallet",
    "Sunglasses",
    "Keyboard",
    "Mouse",
    "Charger",
    "Remote",
    "Pillow",
    "Water Bottle",
  ],

  Random_Funny: [
    "Toilet",
    "Chicken Nugget",
    "Potato",
    "Traffic Jam",
    "Broken Charger",
    "Mosquito",
    "Alarm Clock",
    "Mom's Slipper",
    "Ugly Sweater",
    "Cracked Phone",
    "Lost Sock",
    "School Principal",
    "Nosy Neighbor",
    "Group Project",
    "Monday Morning",
  ],
};

export function pickRandomCategoryAndWord(): {
  category: string;
  word: string;
} {
  const categories = Object.keys(WORD_BANK);
  const category = categories[Math.floor(Math.random() * categories.length)];
  const words = WORD_BANK[category];
  const word = words[Math.floor(Math.random() * words.length)];

  return { category, word };
}